### ISSUE TITLE
[BUG] - sqlite3.OperationalError: attempt to write a readonly database

### ISSUE THREAD

**Issue by peachkeel** [Quansight/ragna#190]
### Bug description

Admittedly, I'm pushing Ragna to the limits, but this error was in the log after uploading over 2k documents into the system. It doesn't seem to have impacted system performance (i.e., the system continues running) and appears to involve ChromaDB's telemetry feature.

### How to reproduce the bug?

I'm unsure how to reproduce the bug. Here is the full dump:

```
ERROR:huey:Unhandled exception in task fef3ca77-d786-4459-a3da-a522175cf737.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/huey/api.py", line 382, in _execute
    task_value = task.execute()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/huey/api.py", line 807, in execute
    return func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ragna/core/_queue.py", line 43, in execute
    return fn(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ragna/source_storages/_chroma.py", line 67, in store
    collection.add(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/chromadb/api/models/Collection.py", line 100, in add
    self._client._add(ids, self.id, embeddings, metadatas, documents)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/chromadb/api/segment.py", line 328, in _add
    self._validate_embedding_record(coll, r)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/chromadb/api/segment.py", line 716, in _validate_embedding_record
    self._validate_dimension(collection, len(record["embedding"]), update=True)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/chromadb/api/segment.py", line 728, in _validate_dimension
    self._sysdb.update_collection(id=id, dimension=dim)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/chromadb/db/mixins/sysdb.py", line 600, in update_collection
    result = cur.execute(sql, params)
sqlite3.OperationalError: attempt to write a readonly database
INFO:huey.consumer:All workers have stopped.
INFO:huey.consumer:Consumer exiting.
```

### Versions and dependencies used

Ragna v0.1.1

**Comment by pmeier** [comment]
> involve ChromaDB's telemetry feature.

I don't think that is the case. The telemetry is just wrapping the database calls to enable tracing. Anyway, I think that is something that you should report upstream as this is nothing that we can fix. Just note that when you say "2k+ documents" you mean actual multipage documents. In Chroma lingo a "document" is one text that is stored in the database. On Ragna side, that would be a chunk:

https://github.com/Quansight/ragna/blob/dc497ef4768b8f8bd4d5c3736eb1d67b27050387/ragna/source_storages/_chroma.py#L58

https://github.com/Quansight/ragna/blob/dc497ef4768b8f8bd4d5c3736eb1d67b27050387/ragna/source_storages/_chroma.py#L67-L71

Since we by default chunk with a 500 token window and 250 token overlap, the number of Chroma documents is orders of magnitude higher than the number of documents that you upload to ragna. For a rough estimate, you can use 3 chunks per page.

**Comment by peachkeel** [comment]
You're right, @pmeier. The problem might be deeper and my terminology isn't accurate. When I say "2k+ documents" I mean the number of files I uploaded to Ragna via the file chooser. Underneath, given the chunking, there is a lot more being stored.

**Comment by pmeier** [comment]
Here is a snippet that you can run to get a better sense of the amount of Chroma documents / Ragna chunks that you are trying to store:

```python
from pathlib import Path

from ragna.core import Config, LocalDocument
from ragna.source_storages._vector_database import VectorDatabaseSourceStorage


class VDB(VectorDatabaseSourceStorage):
    def retrieve(self, documents, prompt):
        pass

    def store(self, documents):
        pass


vdb = VDB(Config())

num_documents = 0
num_chunks = 0
for path in Path("/home/philip/Downloads/10k").rglob("*.pdf"):
    num_documents += 1
    for chunk in vdb._chunk_pages(
        LocalDocument(path).extract_pages(), chunk_size=500, chunk_overlap=250
    ):
        num_chunks += 1

print(f"Extracted {num_chunks=} from {num_documents=}")
```

If they upstream wontfix for some reason, we could actually batch our document adding for example, by not adding more than 10k chunks at a time.

**Comment by peachkeel** [comment]
@pmeier,

My colleague, @tengal_teemo, and I ran your code. Here are the results:

`Extracted num_chunks=40942 from num_documents=2227`

In doing so, we discovered a huge performance discrepancy between running Ragna on a virtual sever versus a local machine. We suspect that the virtual server was severely CPU-throttled during the initial run, which may have contributed to the error.

Regardless, I've upstreamed this issue as https://github.com/chroma-core/chroma/issues/1441 (see mention above).

**Comment by pmeier** [comment]
Closing as we figured out in chroma-core/chroma#1441 that the issue was coming from the fact that we had multiple worker processes. This is no problem in the future since in #205 we removed the task queue and thus the need for workers in general.
